### ISSUE TITLE
Refactor Module-Level Constants to Enums and Classes

### ISSUE THREAD

**Issue by ShearStress021** [AegisNimbus/PuckMaster#1]
![Screenshot 2024-10-12 151352](https://github.com/user-attachments/assets/fbba1b61-0339-4df7-b381-f504a7b20f0d)

** The current codebase utilizes module-level constants for defining various settings, configurations, and related values. While this approach is straightforward, it can lead to issues with organization, readability, and type safety as the project grows. **

**Comment by Ojas-Arora** [comment]
@ShearStress021 Tell the solution that you will provide for this.

**Comment by ShearStress021** [comment]
i would cluster related constants together with either enum, class or namedtuples considering the relationship and datatype of the constants

**Comment by Ojas-Arora** [comment]
@ShearStress021 Ok, Issue assigned to you.

**Comment by Ojas-Arora** [comment]
@ShearStress021 What's the progress on this issue?

**Comment by ShearStress021** [comment]
I’m going to work on the issue this weekend. I got a little busy over the past few days. can please also give the explanation on how to play the game.

**Comment by Ojas-Arora** [comment]
@ShearStress021 U just neeed to run the main.py and make sure all the requirements libraries are installed.

**Comment by ShearStress021** [comment]
the game is running but i think on the help icon instructions on how to play the game are needed

**Comment by Ojas-Arora** [comment]
The given Instructions are sufficient to know how to play game if u have some more instructions that can be added u can add so.
