### ISSUE TITLE
Feat: Leaderboard system for high scores

### ISSUE THREAD

**Issue by yazdanhaider** [AegisNimbus/PuckMaster#2]
### Describe the feature

# Feature
Added a leaderboard system for high scores to the Air Hockey game. Also the leaderboard will be updated after each game, and players can view it from the start screen or the end screen. The leaderboard data will be stored in a JSON file, so it persists between game sessions.

Should I move forward with creating a PR?

### Add ScreenShots

<img width="1201" alt="Screenshot 2024-10-14 at 7 16 09 PM" src="https://github.com/user-attachments/assets/127908d5-63e3-4f15-a651-1cde35039915">
<img width="1201" alt="Screenshot 2024-10-14 at 7 30 32 PM" src="https://github.com/user-attachments/assets/e4f22501-b3fd-4e3d-b211-f01b2fe72e50">

### Record

- [X] I agree to follow this project's Contributing.md
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue

**Comment by Ojas-Arora** [comment]
@yazdanhaider Issue assigned to you. Remember to follow the rules given in the Contributing.md file.
