### ISSUE TITLE
Feat: Temporary power-ups 

### ISSUE THREAD

**Issue by yazdanhaider** [AegisNimbus/PuckMaster#4]
### Describe the feature

Power-ups where user can use temporary power-ups that appear on the field, such as speed boosts, larger paddles, or a temporary force field. Power-ups will spawn randomly on the field every 15 seconds. When a paddle collides with a power-up, it will gain the corresponding effect for 7 seconds. 
# PowerUps
**Speed boost (red):** Increases paddle speed by 50%
**Size increase (green):** Increases paddle size by 30%
**Shield (blue):** Adds a temporary shield around the paddle.

Should I move forward with creating a PR?

### Add ScreenShots

<img width="1201" alt="Screenshot 2024-10-14 at 9 13 29 PM" src="https://github.com/user-attachments/assets/8388a71e-aa02-473b-9739-9bb167a19524">
<img width="1201" alt="Screenshot 2024-10-14 at 9 20 45 PM" src="https://github.com/user-attachments/assets/4ad00c2c-4699-4376-bfad-fdf56bf2284f">
<img width="1201" alt="Screenshot 2024-10-14 at 9 20 53 PM" src="https://github.com/user-attachments/assets/e1f34dd2-383c-4ae6-b635-9edd94e05f0d">
<img width="1201" alt="Screenshot 2024-10-14 at 9 21 08 PM" src="https://github.com/user-attachments/assets/12eecf6c-048e-4507-9521-d9be9a3a1b94">

### Record

- [X] I agree to follow this project's Contributing.md
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue

**Comment by Ojas-Arora** [comment]
@yazdanhaider Issue assigned to you.

**Comment by yazdanhaider** [comment]
> @yazdanhaider Issue assigned to you.

Please create PR so i can push the changes into it.
