### ISSUE TITLE
DOC: CONTRIBUTING.md Documentation Error

### ISSUE THREAD

**Issue by yazdanhaider** [AegisNimbus/PuckMaster#5]
### What's wrong with the existing documentation

# Description
Navigation of the project directory in the CONTRIBUTING.md is specifying in the wrong directory which is not available in the directory folder of PuckMaster.

# Issue 
Navigate to the project directory. **cd ML-Alchemy**

# Solution
Navigate to the project directory. **cd PuckMaster**

### Add ScreenShots

<img width="572" alt="Screenshot 2024-10-14 at 9 29 59 PM" src="https://github.com/user-attachments/assets/ec353f95-6f9b-4346-996f-7b77388b2675">

### Record

- [X] I agree to follow this project's Contributing.md
- [X] I'm a Hacktoberfest contributor
- [X] I want to work on this issue

**Comment by Ojas-Arora** [comment]
Not needed
